# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Go environment
      uses: actions/setup-go@v2.1.2
      with:
        go-version: 1.13
    - name: Test
      run: go test ./cmd/go-sudoku/... -cover
    - name: Benchmark
      run: go test ./cmd/go-sudoku/solver/... -run=^$ -bench ^Benchmark
    - name: Build
      run: go build -o output/go-sudoku cmd/go-sudoku/main.go
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: go-sudoku
        path: output/go-sudoku
